import os
from datetime import datetime
from langchain_google_genai import ChatGoogleGenerativeAI


def get_model():
    return ChatGoogleGenerativeAI(
        model="gemini-2.5-flash-lite",
        google_api_key=os.getenv("GOOGLE_API_KEY"),
        temperature=0.4
    )


def get_confidence(avg_score, used_fallback):
    if used_fallback:
        return "LOW"
    if avg_score >= 0.75:
        return "HIGH"
    if avg_score >= 0.55:
        return "MEDIUM"
    return "LOW"


def get_top_sources(scored_sources, limit=10):
    """filter to decent sources only and return the top ones"""
    good = [s for s in scored_sources if s.get("score", 0) >= 0.4]
    good.sort(key=lambda x: x.get("score", 0), reverse=True)
    return good[:limit]


def writer_node(state):
    print("\n[writer] writing the report...")

    model = get_model()
    top_sources = get_top_sources(state["scored_sources"])
    confidence = get_confidence(state["avg_score"], state["used_fallback"])

    # build a numbered list of sources to pass to the model
    sources_text = ""
    for i, s in enumerate(top_sources, 1):
        sources_text += f"\n[{i}] {s['title']}\nURL: {s['url']}\n{s['content'][:800]}\n"

    fallback_warning = ""
    if state["used_fallback"]:
        fallback_warning = "\nNote: source quality was low after 3 search attempts. Some parts of this report may be based on general knowledge rather than the sources below.\n"

    prompt = f"""
Write a research report answering this question: {state['question']}

Use the sources below. For every fact you write, add a citation like [1] or [2] using the source number.

{fallback_warning}

Sources:
{sources_text}

Write the report in this format:

## Summary
2-3 sentences overview

## Findings

### [topic from sub-question 1]
write findings here with [1] citations

### [topic from sub-question 2]
...

## Key Takeaways
focus on actionable advice or the 'bottom line' for a policymaker, rather than just summarizing the findings again.
bullet points with the most important insights

## References
[1] title - url
[2] title - url
...

Keep it under 800 words. Only cite sources that are actually in the list above.
"""

    response = model.invoke(prompt)
    report_body = response.content.strip()

    # add a small footer with metadata
    footer = f"\n\n---\n*Generated by ResearchPilot on {datetime.now().strftime('%Y-%m-%d')}*\n"
    footer += f"*Confidence: {confidence} | Search loops: {state['loop_count']} | Sources checked: {len(state['scored_sources'])} | Avg quality: {state['avg_score']:.2f}*"

    final_report = report_body + footer

    print(f"  [writer] done. confidence: {confidence}")

    return {
        **state,
        "report": final_report,
        "confidence": confidence
    }
